POST http://143.198.141.231:3130/login_password HTTP/1.1
Content-Type: application/json

{
    "email": "nodywelete3@gmail.com",
    "password": "Qwerty1#"
}

# http://192.168.1.38:2120/ 

# GET http://192.168.1.38:2120/employee_info_operation?institution_code=C1624 HTTP/1.1
# Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY1Nzc5MTU3NiwianRpIjoiY2Y1NTUzNWQtODFiNC00ZGYwLWJjNDUtMDk0Yzk4MThhMjc2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6eyJlbWFpbCI6Im5vZHl3ZWxldGUzQGdtYWlsLmNvbSIsImNvdW50cnlfY29kZSI6IjIzNCIsInBob25lIjoiMDgxMDgzNzAwNzMiLCJidXNpbmVzc19uYW1lIjoiSVRlY2hGb3IiLCJjb21wYW55X3VybCI6Imh0dHA6Ly9pdGVjaGZvci52ZXJpcGF5Lm5nIiwidmFsaWRhdGlvbiI6MSwiaW5zdGl0dXRpb25fY29kZSI6IkMxNjI0IiwibmFtZSI6IklUZWNoRm9yIiwic2V0dXAiOjEsInNpZ251cF9zdGFnZSI6NCwiYWN0aXZhdGVkIjp0cnVlLCJhZG1pbl9jb2RlIjoiOWIyYjIzMzEyMyIsImFkZHJlc3MiOiJIb3VzZSA0NiIsImNpdHkiOiJBcG8iLCJjb3VudHJ5IjoiTmlnZXJpYSIsInN0YXRlIjoiQWJ1amEiLCJ6aXBfY29kZSI6IjEyMzQ1NiJ9LCJuYmYiOjE2NTc3OTE1NzYsImV4cCI6MTY1NzgzNDc3Nn0.rIW2XBL7mpdfSy6BS1a-9Im-f9KpyfW050-pyPsXMa8

# POST http://105.112.130.227:2121/setup_under_service HTTP/1.1
# Content-Type: application/json

# { 
#     "setup_codes": [{"setup_code":"7e2d204e0f"}],
#     "service_code": "9361fe7a86"
# }

# GET http://192.168.1.51:2120/staff_type?institution_code=C1624 HTTP/1.1
# Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY1NjMyMjE4MSwianRpIjoiMmMxZGE4Y2QtMzU3YS00OGE2LWEzN2EtZWE5NjNiN2E1ZDQ0IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6eyJlbWFpbCI6Im5vZHl3ZWxldGUzQGdtYWlsLmNvbSIsImNvdW50cnlfY29kZSI6IjIzNCIsInBob25lIjoiMDgxMDgzNzAwNzMiLCJidXNpbmVzc19uYW1lIjoiSVRlY2hGb3IiLCJjb21wYW55X3VybCI6Imh0dHA6Ly9pdGVjaGZvci52ZXJpcGF5Lm5nIiwidmFsaWRhdGlvbiI6MSwiaW5zdGl0dXRpb25fY29kZSI6IkMxNjI0IiwibmFtZSI6IklUZWNoRm9yIiwic2V0dXAiOjEsInNpZ251cF9zdGFnZSI6NCwiYWN0aXZhdGVkIjp0cnVlLCJhZG1pbl9jb2RlIjoiOWIyYjIzMzEyMyIsImFkZHJlc3MiOiJIb3VzZSA0NiIsImNpdHkiOiJBcG8iLCJjb3VudHJ5IjoiTmlnZXJpYSIsInN0YXRlIjoiQWJ1amEiLCJ6aXBfY29kZSI6IjEyMzQ1NiJ9LCJuYmYiOjE2NTYzMjIxODEsImV4cCI6MTY1NjM2NTM4MX0.n2vwCjhDjR-inYQeeY1lw78VghWnobZWnRYl7P5I5Gg

# GET http://192.168.1.38:2120/employee_info_operation?institution_code=C1624&search=false&value=08108370073 HTTP/1.1
# Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY1NjUxNTA5NSwianRpIjoiNTNjZjc2ZDgtMjM1NS00NmZkLTkwOWItNWNhYTFjZGM2YWQ4IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6eyJlbWFpbCI6Im5vZHl3ZWxldGUzQGdtYWlsLmNvbSIsImNvdW50cnlfY29kZSI6IjIzNCIsInBob25lIjoiMDgxMDgzNzAwNzMiLCJidXNpbmVzc19uYW1lIjoiSVRlY2hGb3IiLCJjb21wYW55X3VybCI6Imh0dHA6Ly9pdGVjaGZvci52ZXJpcGF5Lm5nIiwidmFsaWRhdGlvbiI6MSwiaW5zdGl0dXRpb25fY29kZSI6IkMxNjI0IiwibmFtZSI6IklUZWNoRm9yIiwic2V0dXAiOjEsInNpZ251cF9zdGFnZSI6NCwiYWN0aXZhdGVkIjp0cnVlLCJhZG1pbl9jb2RlIjoiOWIyYjIzMzEyMyIsImFkZHJlc3MiOiJIb3VzZSA0NiIsImNpdHkiOiJBcG8iLCJjb3VudHJ5IjoiTmlnZXJpYSIsInN0YXRlIjoiQWJ1amEiLCJ6aXBfY29kZSI6IjEyMzQ1NiJ9LCJuYmYiOjE2NTY1MTUwOTUsImV4cCI6MTY1NjU1ODI5NX0.RDDyYK_15gmMFOU82DcCTAbkcc2MXI40hdDKFAPOgJ8


# GET http://192.168.0.151:2120/qualification?institution_code=C1624 HTTP/1.1
# Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY1Nzc5MTU3NiwianRpIjoiY2Y1NTUzNWQtODFiNC00ZGYwLWJjNDUtMDk0Yzk4MThhMjc2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6eyJlbWFpbCI6Im5vZHl3ZWxldGUzQGdtYWlsLmNvbSIsImNvdW50cnlfY29kZSI6IjIzNCIsInBob25lIjoiMDgxMDgzNzAwNzMiLCJidXNpbmVzc19uYW1lIjoiSVRlY2hGb3IiLCJjb21wYW55X3VybCI6Imh0dHA6Ly9pdGVjaGZvci52ZXJpcGF5Lm5nIiwidmFsaWRhdGlvbiI6MSwiaW5zdGl0dXRpb25fY29kZSI6IkMxNjI0IiwibmFtZSI6IklUZWNoRm9yIiwic2V0dXAiOjEsInNpZ251cF9zdGFnZSI6NCwiYWN0aXZhdGVkIjp0cnVlLCJhZG1pbl9jb2RlIjoiOWIyYjIzMzEyMyIsImFkZHJlc3MiOiJIb3VzZSA0NiIsImNpdHkiOiJBcG8iLCJjb3VudHJ5IjoiTmlnZXJpYSIsInN0YXRlIjoiQWJ1amEiLCJ6aXBfY29kZSI6IjEyMzQ1NiJ9LCJuYmYiOjE2NTc3OTE1NzYsImV4cCI6MTY1NzgzNDc3Nn0.rIW2XBL7mpdfSy6BS1a-9Im-f9KpyfW050-pyPsXMa8
